# config.yaml

server:
  interface: "eth0"              # Network interface to bind services
  ip: "192.168.1.1"              # IP address of the DHCP server and default gateway
  subnet_mask: "255.255.255.0"   # Subnet mask
  router: "192.168.1.1"           # Default gateway
  dns_servers:
    - "8.8.8.8"
    - "8.8.4.4"                    # DNS servers
  ip_pool:
    start: "192.168.1.100"
    end: "192.168.1.200"
  lease_time: 3600                 # Lease time in seconds (1 hour)

routing:
  static_routes:
    - destination: "0.0.0.0/0"
      gateway: "192.168.1.1"
    - destination: "10.0.0.0/24"
      gateway: "192.168.1.2"

dynamic_routing:
  protocol: "RIP"                  # Currently supports "RIP"
  neighbors:
    - "192.168.1.2"
    - "192.168.1.3"

multicast:
  groups:
    - "224.0.0.1"
    - "224.0.0.251"

udp_service:
  echo_server:
    ip: "192.168.1.1"
    port: 9999

snmp_manager:
  version: "1"                     # SNMP version (1 or 2c)
  community: "public"              # Community string for SNMPv1/v2c
  users:                           # SNMPv3 users (if using SNMPv3)
    - username: "admin"
      auth_protocol: "SHA"
      auth_password: "authPass123"
      priv_protocol: "AES"
      priv_password: "privPass123"
  agents:
    - ip: "235.432.8.4"
      port: 161
    - ip: "235.432.8.5"
      port: 161
  mibs:
    - name: "MIB-II"
      file: "mibs/MIB-II.txt"
    - name: "Custom-MIB"
      file: "mibs/Custom-MIB.txt"

logging:
  level: "INFO"                    # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  file: "enterprise_networking_suite.log"  # Log file path