FROM node:20.4.0-bullseye-slim
EXPOSE 6000
WORKDIR /proxy
RUN apt-get -y update; apt-get -y install curl libzmq3-dev openssl
COPY src/dock/org/package.json /proxy
COPY src/lib /proxy/src/lib
RUN npm i
CMD node src/lib/net --run=proxy
