# Dockerfile

FROM golang:1.20-alpine

# Set environment variables.
ENV GO111MODULE=on

# Install necessary packages.
RUN apk update && apk add --no-cache git

# Set work directory.
WORKDIR /app

# Copy go.mod and go.sum.
COPY go.mod go.sum ./

# Download dependencies.
RUN go mod download

# Copy the source code.
COPY . .

# Build the application.
RUN go build -o link_layer cmd/main.go

# Expose necessary ports (if any).
# EXPOSE 162

# Run the application.
CMD ["./link_layer", "-config", "configs/config.yaml"]